model_id: "C:\\_dev\\comfy\\ComfyUI\\models\\checkpoints\\kohaku-v2.1.safetensors"
t_index_list: [32, 45]
width: 512
height: 512
device: "cuda"
dtype: "float16"

# Generation parameters
prompt: "a beautiful landscape, highly detailed, masterpiece"
negative_prompt: "blurry, low quality, distorted"
guidance_scale: 1.2
num_inference_steps: 50

# Advanced parameters
pipeline_type: "sd1.5"
use_lcm_lora: true
use_tiny_vae: true
acceleration: "xformers"
cfg_type: "self"
seed: 42

# ControlNet configurations
controlnets:
  - model_id: "lllyasviel/control_v11p_sd15_canny"
    conditioning_scale: 1.0
    preprocessor: "canny"
    preprocessor_params:
      low_threshold: 100
      high_threshold: 200
    enabled: true 