model_id: "C:\\_dev\\comfy\\ComfyUI\\models\\checkpoints\\kohaku-v2.1.safetensors"
t_index_list: [32, 45]
width: 512
height: 512
device: "cuda"
dtype: "float16"

# Generation parameters
prompt: "a futuristic cityscape, cyberpunk style, neon lights, detailed architecture"
negative_prompt: "blurry, low quality, flat, 2d"
guidance_scale: 1.5
num_inference_steps: 50

# Advanced parameters
use_lcm_lora: true
use_tiny_vae: true
acceleration: "xformers"
cfg_type: "self"
seed: 789

# ControlNet configuration
controlnets:
  - model_id: "lllyasviel/control_v11f1p_sd15_depth"
    conditioning_scale: 1.2
    preprocessor: "depth"
    preprocessor_params:
      model_name: "Intel/dpt-large"
      detect_resolution: 512
      image_resolution: 512
    enabled: true 