model_id: "C:\\_dev\\comfy\\ComfyUI\\models\\checkpoints\\kohaku-v2.1.safetensors"
t_index_list: [0,16,32]
width: 512
height: 512
device: "cuda"
dtype: "float16"

# Generation parameters
prompt: "an anime render of a girl with purple hair, masterpiece"
negative_prompt: "blurry, low quality, flat, 2d"
guidance_scale: 1.1
num_inference_steps: 50

# Advanced parameters
use_lcm_lora: true
use_tiny_vae: true
acceleration: "xformers"
cfg_type: "self"
seed: 789

# ControlNet configuration with TensorRT Depth Anything
controlnets:
  - model_id: "lllyasviel/control_v11f1p_sd15_depth"
    conditioning_scale: 0.5
    preprocessor: "depth_tensorrt"
    preprocessor_params:
      engine_path: "C:\\_dev\\comfy\\ComfyUI\\models\\tensorrt\\depth-anything\\depth_anything_vits14-fp16.engine"
      detect_resolution: 518
      image_resolution: 512
    enabled: true 