model_id: "C:\\_dev\\comfy\\ComfyUI\\models\\checkpoints\\kohaku-v2.1.safetensors"
t_index_list: [0,16, 32, 45]
width: 512
height: 512
device: "cuda"
dtype: "float16"

# Generation parameters
prompt: "beautiful anime girl, detailed line art style, clean lines, masterpiece"
negative_prompt: "blurry, low quality, messy lines, sketchy"
guidance_scale: 1.2
num_inference_steps: 50

# Advanced parameters
use_lcm_lora: true
use_tiny_vae: true
acceleration: "xformers"
cfg_type: "self"
seed: 456

# Lineart ControlNet configuration (SD 1.5 based)
controlnets:
  - model_id: "lllyasviel/control_v11p_sd15s2_lineart_anime"
    conditioning_scale: 1.0
    preprocessor: "lineart"
    preprocessor_params:
      detect_resolution: 512
      image_resolution: 512
      coarse: false
      anime_style: true
    enabled: true 