model_id: "C:\\_dev\\comfy\\ComfyUI\\models\\checkpoints\\kohaku-v2.1.safetensors"
t_index_list: [32, 45]
width: 512
height: 512
device: "cuda"
dtype: "float16"

# Generation parameters
prompt: "a person standing in a modern room, photorealistic, detailed"
negative_prompt: "blurry, low quality, distorted, cartoon"
guidance_scale: 1.3
num_inference_steps: 50

# Advanced parameters
pipeline_type: "sd1.5"
use_lcm_lora: true
use_tiny_vae: true
acceleration: "xformers"
cfg_type: "self"
seed: 123

# Multiple ControlNet configurations
controlnets:
  # OpenPose for human pose
controlnets:

controlnets:
  - model_id: "lllyasviel/control_v11f1e_sd15_tile"
    conditioning_scale: 0.3
    preprocessor: "passthrough"
    preprocessor_params:
      image_resolution: 512
    enabled: true 

  # Depth for spatial structure
  - model_id: "lllyasviel/control_v11f1p_sd15_depth"
    conditioning_scale: 0.5
    preprocessor: "depth_tensorrt"
    preprocessor_params:
      engine_path: "C:\\_dev\\comfy\\ComfyUI\\models\\tensorrt\\depth-anything\\depth_anything_vits14-fp16.engine"
      detect_resolution: 518
      image_resolution: 512
    enabled: true 