model_id: "C:\\_dev\\comfy\\ComfyUI\\models\\checkpoints\\sd_turbo.safetensors"
t_index_list: [24,27]
width: 512
height: 512
device: "cuda"
dtype: "float16"

# Generation parameters
prompt: "an anime render of a girl with purple hair, masterpiece"
negative_prompt: "blurry, low quality, flat, 2d"
guidance_scale: 1.041
num_inference_steps: 50

# Temporal consistency parameters
frame_buffer_size: 1
use_denoising_batch: true
delta: 0.7

# Advanced parameters
pipeline_type: "sdturbo"
use_lcm_lora: true
use_tiny_vae: true
acceleration: "tensorrt"
cfg_type: "self"
seed: 789

# ControlNet configuration with Browser preprocessor (client-side processing)
controlnets:
  - model_id: "thibaud/controlnet-sd21-openpose-diffusers"
    conditioning_scale: 0.711
    preprocessor: "browser"  # Client processes pose detection, server just validates
    preprocessor_params:
      image_resolution: 512
      validate_input: true
      normalize_brightness: false
    enabled: true 

# Example of additional ControlNet (uncomment to enable multiple)
# - model_id: "thibaud/controlnet-sd21-depth-diffusers"
#   conditioning_scale: 0.3
#   preprocessor: "browser"  # Could also be client-processed depth
#   preprocessor_params:
#     image_resolution: 512
#     validate_input: true
#   enabled: true 